services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_LOG_CONSOLE=true
      # To upgrade mariadb from an older version, uncomment the line below
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ${SEAFILE_DB_DATA:-./data-db}:/var/lib/mysql
    networks:
      - seafile-net
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: "10m"
#        max-file: "3"

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net
    logging:
      options:
        max-size: "10m"
#        max-file: "3"

  seafile:
    image: seafileltd/seafile-mc:${SEAFILE_IMAGE_VERSION:-12.0-latest}
    container_name: seafile
    restart: unless-stopped
    volumes:
      - ${SEAFILE_SHARED_DATA:-./data}:/shared
    env_file:
      - .env
    user: "466367:466367" #hetzner-box uid for ownership
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8082:8082"
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - seafile-net
    logging:
      options:
        max-size: "10m"
#        max-file: "3"

networks:
  seafile-net:
    name: seafile-net
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
